# Generated by Django 5.1.7 on 2025-07-30 03:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0003_rename_categorymodel_category_product_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="image",
            field=models.ImageField(upload_to="products/%Y%m&d/"),
        ),
    ]
